name: KiddycraftFarmpig
main: de.kiddycraft.farmpig.FarmPigPlugin
version: 69
description: For all glorious kiddies that lack so much creativity that they even copy your pork farm.
author: Kevin
depend:

commands:
  farmpig:
    description: Selectively enable nag feature. Use /nagmod to get list of modules.
    usage: |
      /farmpig list - lists all active farmpigs and allows managing.
      /farmpig add <type> [name] - creates a new farmpig at the current position with an optional name.
    permission: kiddycraft.farmpig

permissions:
  kiddycraft.farmpig:
    description: Grants all permissions to ops
